### ISSUE TITLE
Decide if the Device ID is too long and make shorter if appropriate.

### ISSUE THREAD

**Issue by devhawk** [gosqasorg/asset-provenance-tracking#5]
devhawk comment: The initial demo app used SHA 256 as the device key hashing algorithm. This is clearly overkill, given that the secret key size is also 256 bits long. As long as we pick some well-known standard hashing algorithm - even a non cryptographic hash like [MurmurHash](https://en.wikipedia.org/wiki/MurmurHash) or [FNV](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function) - this should be an easy change.

**Comment by devhawk** [comment]
This is a design question, so I've assigned it to @RobertLRead. A few notes:

* both the original demo and the `dev` branch are using AES-256 for encryption, so the device secret key is 256 bits / 32 bytes long
* The original demo used SHA 256 for hashing. using a 256 bit hash for a 256 bit key does seem like overkill
* in the dev branch, the device ID is generated from the hash via 64-bit FNV. This enables the device ID to be represented as a 64 bit integer (bigint in TS), which is likely better for DB operations than a hex string

**Comment by RobertLRead** [comment]
Dear @devhawk,

That seems appropriate to me at first blush, but my question is would it give our users more confidence if we used a cryptographic hash?  I want to be able to say "the database is publicly readable, and nobody can decrypt the provenance without a key or discover keys from the database." I don't know if FNV would convince people of that. On the other hand, our goal here is to have thousands of devices; if one is compromised, it is a smallish-loss.  I seek your advice, Harry.

**Comment by RobertLRead** [comment]
Dear @devhawk,

I'm moving this out of "ready for QA" and back into in progress; not because there is anything wrong with you code, but I think there may have been a lack of clarity in our language (probably my fault.)

We are using a 64-character "key". The key is what is printed on the box; the id is what you are using as the primary key in the database (I think.) The real issue to me is that 64-character key seems to long. There will be times, even if we use QR codes, when people have to type this in. So I ask the question: Can use use 48 or 32 characters instead? Or even less?  

I am not a cryptographer, but my reasoning goes like this: If our system could support a billion objects, that will probably be good enough to support wild success for several years. We of course have to have significantly more keys than objects, otherwise you could guess a key and have it have a good chance of "hitting" some object at random. 

I think a 32 character alphanumeric string has (36^32) possibilities. That is so much larger than a billion that I think we would be safe, and our users would be less likely to object to the keys being so long.

I see no reason to change the approach you have taking to the computation of the public device id as a hash from the key.

**Comment by devhawk** [comment]
We can shorten the encoded device key using a shorter key and/or using more efficient encoding than hex. 

Below is a table showing the three secret key sizes Node supports (256, 192 and 128) encoded in hex, Base64 and [Base58](https://en.bitcoin.it/wiki/Base58Check_encoding). 

|Key type| Example|
|---------|-----|
| 256 bit hex encoded | `23e8992e9ae15bfdf4dd488dd8ba156de9eba43e118d240d541b7152e3f6b34c` |
| 256 bit base 64 encoded | `cIZxin0IeAnGtKEqHkxYdfFfJ18JB6MRNnDL8XxhNJg=` |
| 256 bit base 58 encoded | `3RAysjDmwJA8dd69B4Tukoxn2RNRDEgx6b5ZHVykaj3R` |
| 192 bit hex encoded | `4345babed74aab5e15ea1febf45738d3cd8af884dad046cd` |
| 192 bit base 64 encoded | `FgO2AWCsFf68nV5vZdufab+N/pMg53os` |
| 192 bit base 58 encoded | `78hok1HMgkd7UsrHY42YvpWdhWv3fMaWQ` |
| 192 bit hex encoded | `7e3af60c22a8c99cec099b1b0ffd9d0e` |
| 128 bit hex encoded | `lcIyvH9eYQeSYIu+1g5Gcg==` |
| 128 bit base 58 encoded | `Gb5D3ThYmEsrYytfWQNXXs` |

If manual entry is a high priority scenario, Base58 may be a good choice. 

* about as efficient as Base64
* avoids characters that can appear the same in some fonts (0 vs O, 1 vs I vs l)
* doesn't use padding characters (256 bit base 64 encoded has a single padding `=`, 128 bit base 58 encoded has `==` padding)

**Comment by devhawk** [comment]
Note, base 58 encoded keys will *NOT* have a consistent length. 

Using 256 bit keys as an example
* hex encoded is *always* 64 characters
* base 64 encoding is *always* 44 characters (with the last character a padding `=`)
* base 58 encoding varies from between 32 and 44 characters long

**Comment by RobertLRead** [comment]
Base 58 seems awesome to me!  I had never heard of it.

Let's move forward with that. The variable length does not bother me.

**Comment by devhawk** [comment]
What about key length? If we drop down to 192 bit key, the base 58 encoded key should max out at 32 characters

**Comment by RobertLRead** [comment]
I think we agreeed we could go down to 128 bit keys in our video chat, let's go with that.

**Comment by devhawk** [comment]
switched to `aes-128-cbc` encryption (16 byte key) + base58 encoding
