### ISSUE TITLE
[FEATURE REQUEST] Color-Coding Tags

### ISSUE THREAD

**Issue by noramoor2007** [gosqasorg/asset-provenance-tracking#93]
## Organizing Tags by Implementing a Color Scheme
**Objective**
The objective behind implementing color-coding for a specific set of tags is to enhance the organization and visual clarity of a user's provenance record, thereby facilitating easier recognition of individual tags solely by their assigned colors.

**Proposal**
To achieve this objective, I suggest we generate a list of the 20 most commonly used tag names within the system and assigning colors to each. For instance, tags representing positive elements, such as "received," could be assigned a bright green color, while tags indicating issues like "bug" or "error" could be recognized with a bright red color to attract attention effectively. To streamline the process of tagging and ensure consistency, the system can provide auto-suggestions as users type, guiding them towards using predefined tag names. In instances where users input unconventional tag names like "password" or "fantastic," the system can extract the first three letters (or fewer if necessary), convert them into HEX codes, and utilize the resulting color for the visual effect. For example, if a user inputs "fantastic," the system would derive the HEX code "66616E" (from "fan") and generate a corresponding color:

<img width="656" alt="Screen Shot 2024-02-11 at 5 01 28 PM" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/135470174/38872603-c7d8-48a0-9a36-fe12d9c596e7">

In case of exceptions (i.e., "fancy", "fanning") we can do the first letter, the middle letter, and the last letter instead. To determine whether the derived color is closer to red or green, the program can analyze the HEX code's RGB values. If the color leans towards red, an adjustment can be made by increasing the R (red) value by 50, ensuring that the final color aligns more closely with the intended representation, also to avoid having really dark colors:

<img width="656" alt="Screen Shot 2024-02-11 at 5 22 52 PM" src="https://github.com/gosqasorg/asset-provenance-tracking/assets/135470174/1f0f4ab9-6250-4342-bf3d-db03e3179971">

I have generated a list of all the tags used and the number of instances of each tag. Highlighted in bright yellow are the top 20 most used tags (exceptions excluded). Please feel free to suggest any colors for the tags.

[GOSQAS Tag Color Library](https://docs.google.com/spreadsheets/d/12C1q2EiBDWpHA_-7_XBM6Ovn05QvnYpOZyc1cPayDMk/edit?usp=sharing)

**Comment by RobertLRead** [comment]
Dear @noramoor2007, This is excellent work. I should have seen this before our last meeting, or I would have lauded it then.

I do not think, however, that we should do continuous interpretation which you propose, although it is quite creative. I think we should do something a bit simpler. The spreadsheet you have created is a wonderful start.  Basically, I think we should just a set of, say 100 colors. They should be separated into "light" and "dark", in order to determine if the text in them should be rendered in black (for the light ones) or white (for the dark ones.)  As you have already suggested, the most frequent tags should be intentionally mapped. For tags not in the most frequent set (let's say the top 25), we can use your scheme, but instead of mapping directly to a color as you cleverly do, we just "hash" the string itself into a number between 1-100 (that being the number of colors we have designed.) Then each string will always get the same color, but except for the most frequent it will have no intentional meaning. However, it will be guaranteed to be attractive, and to be informative, in that if the users learn to look for a given color (perhaps because they are using a LOtE), it will be stable and meaningful.

**Comment by RobertLRead** [comment]
This has been fixed by PR https://github.com/gosqasorg/asset-provenance-tracking/pull/105
